// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzdNFzQBzI7eBCzVhHKA0CyUXkA5CpkHQ',
    appId: '1:226106284414:web:cb7ceb8aeab94554a33b2f',
    messagingSenderId: '226106284414',
    projectId: 'flutter-lab-test-91254',
    authDomain: 'flutter-lab-test-91254.firebaseapp.com',
    storageBucket: 'flutter-lab-test-91254.firebasestorage.app',
    measurementId: 'G-GLNZXWMCVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBvA26EQxzMPG_p3Tnqbt5RZQVYJm1Qo',
    appId: '1:226106284414:android:f429065657a44bcaa33b2f',
    messagingSenderId: '226106284414',
    projectId: 'flutter-lab-test-91254',
    storageBucket: 'flutter-lab-test-91254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0iye5jsZQqerLLgXPjuhy-ncb4m2thPM',
    appId: '1:226106284414:ios:aeabb6d60b01ee32a33b2f',
    messagingSenderId: '226106284414',
    projectId: 'flutter-lab-test-91254',
    storageBucket: 'flutter-lab-test-91254.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0iye5jsZQqerLLgXPjuhy-ncb4m2thPM',
    appId: '1:226106284414:ios:aeabb6d60b01ee32a33b2f',
    messagingSenderId: '226106284414',
    projectId: 'flutter-lab-test-91254',
    storageBucket: 'flutter-lab-test-91254.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzdNFzQBzI7eBCzVhHKA0CyUXkA5CpkHQ',
    appId: '1:226106284414:web:7123472a0771da2da33b2f',
    messagingSenderId: '226106284414',
    projectId: 'flutter-lab-test-91254',
    authDomain: 'flutter-lab-test-91254.firebaseapp.com',
    storageBucket: 'flutter-lab-test-91254.firebasestorage.app',
    measurementId: 'G-P6KHBB70JT',
  );
}
